In [1]:
import pandas as pd
import numpy as np
from pandas import ExcelWriter
from pandas import ExcelFile
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
import os
from supervised.automl import AutoML

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [4]:
data1 = pd.read_csv('data/cleaned_wide.csv', index_col='Unnamed: 0')

In [5]:
data1

Species Strain    Samples    Ethyl Acetate  Ethanol  \
3       SA   SA_A  SA.A_TSB_A        465374.0  1027715   
4       SA   SA_A  SA.A_TSB_B        193151.0  1050974   
5       SA   SA_A  SA.A_TSB_C        403286.0  1850391   
6       SA   SA_A  SA.A_TSB_D        129833.0  5140770   
7       SA   SA_A  SA.A_TSB_E        117105.0  3422557   
..     ...    ...         ...             ...      ...   
82      EC   EC_B  EC.B_TSB_A        119313.0  1364553   
83      EC   EC_B  EC.B_TSB_B        128397.0  1451138   
84      EC   EC_B  EC.B_TSB_C        309004.0  5650813   
85      EC   EC_B  EC.B_TSB_D        548442.0  3588158   
86      EC   EC_B  EC.B_TSB_E        339404.0  3962927   

    Propanoic acid, ethyl ester  2-Pentanone  Decane  Methyl Isobutyl Ketone  \
3                           NaN      1289650  800581                324424.0   
4                           NaN       504113  294680                189630.0   
5                           NaN      1169501      15                228163.0   
6                           NaN      1926072  124282                     0.0   
7                           NaN       246751       0                     0.0   
..                          ...          ...     ...                     ...   
82                          0.0       169495       0                     NaN   
83                          0.0       359499       0                     NaN   
84                          0.0       875905       0                     NaN   
85                          0.0       637563       0                     NaN   
86                          0.0      2988409  348154                     NaN   

    Amylene hydrate  ...  1-Dodecanol  Methyl tetradecanoate  \
3             73015  ...          NaN                    NaN   
4                 0  ...          NaN                    NaN   
5             73558  ...          NaN                    NaN   
6            188367  ...          NaN                    NaN   
7                 0  ...          NaN                    NaN   
..              ...  ...          ...                    ...   
82                0  ...     289615.0                    0.0   
83                0  ...     749942.0                    0.0   
84           109170  ...     479315.0                    0.0   
85            60834  ...    2750809.0                    0.0   
86           694251  ...    8172616.0               698476.0   

     2-Pentadecanone  Tetradecanoic acid, ethyl ester  Hexadecanal  \
3                NaN                              NaN          NaN   
4                NaN                              NaN          NaN   
5                NaN                              NaN          NaN   
6                NaN                              NaN          NaN   
7                NaN                              NaN          NaN   
..               ...                              ...          ...   
82               0.0                              0.0          0.0   
83               0.0                              0.0          0.0   
84               0.0                              0.0          0.0   
85               0.0                              0.0          0.0   
86          382222.0                              0.0          0.0   

    n-Tridecan-1-ol  1-Tetradecanol  n-Pentadecanol   1-Hexadecanol  \
3               NaN             NaN             NaN             NaN   
4               NaN             NaN             NaN             NaN   
5               NaN             NaN             NaN             NaN   
6               NaN             NaN             NaN             NaN   
7               NaN             NaN             NaN             NaN   
..              ...             ...             ...             ...   
82              0.0             0.0             0.0             0.0   
83              0.0         78672.0             0.0             0.0   
84              0.0         84426.0             0.0             0.0   
85              0.0      

In [11]:
samples = data1['Samples ']
samples = np.array(samples)
i = 0
medium = []
while i < len(samples):
    split = samples[i].split('_')
    medium.append(split[1])
    i += 1

In [12]:
medium

['TSB',
 'TSB',
 'TSB',
 'TSB',
 'TSB',
 'TSB',
 'TSB',
 'TSB',
 'TSB',
 'TSB',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'TSB',
 'TSB',
 'TSB',
 'TSB',
 'TSB',
 'TSB',
 'TSB',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'BHI',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'LB',
 'TSB',
 'TSB',
 'TSB',
 'TSB',
 'TSB',
 'TSB',
 'TSB',
 'TSB',
 'TSB',
 'TSB']

In [14]:
medium = np.array(medium)
data1['Medium'] = medium.tolist()

In [15]:
data1

Species Strain    Samples    Ethyl Acetate  Ethanol  \
3       SA   SA_A  SA.A_TSB_A        465374.0  1027715   
4       SA   SA_A  SA.A_TSB_B        193151.0  1050974   
5       SA   SA_A  SA.A_TSB_C        403286.0  1850391   
6       SA   SA_A  SA.A_TSB_D        129833.0  5140770   
7       SA   SA_A  SA.A_TSB_E        117105.0  3422557   
..     ...    ...         ...             ...      ...   
82      EC   EC_B  EC.B_TSB_A        119313.0  1364553   
83      EC   EC_B  EC.B_TSB_B        128397.0  1451138   
84      EC   EC_B  EC.B_TSB_C        309004.0  5650813   
85      EC   EC_B  EC.B_TSB_D        548442.0  3588158   
86      EC   EC_B  EC.B_TSB_E        339404.0  3962927   

    Propanoic acid, ethyl ester  2-Pentanone  Decane  Methyl Isobutyl Ketone  \
3                           NaN      1289650  800581                324424.0   
4                           NaN       504113  294680                189630.0   
5                           NaN      1169501      15                228163.0   
6                           NaN      1926072  124282                     0.0   
7                           NaN       246751       0                     0.0   
..                          ...          ...     ...                     ...   
82                          0.0       169495       0                     NaN   
83                          0.0       359499       0                     NaN   
84                          0.0       875905       0                     NaN   
85                          0.0       637563       0                     NaN   
86                          0.0      2988409  348154                     NaN   

    Amylene hydrate  ...  Methyl tetradecanoate   2-Pentadecanone  \
3             73015  ...                    NaN               NaN   
4                 0  ...                    NaN               NaN   
5             73558  ...                    NaN               NaN   
6            188367  ...                    NaN               NaN   
7                 0  ...                    NaN               NaN   
..              ...  ...                    ...               ...   
82                0  ...                    0.0               0.0   
83                0  ...                    0.0               0.0   
84           109170  ...                    0.0               0.0   
85            60834  ...                    0.0               0.0   
86           694251  ...               698476.0          382222.0   

    Tetradecanoic acid, ethyl ester  Hexadecanal  n-Tridecan-1-ol  \
3                               NaN          NaN              NaN   
4                               NaN          NaN              NaN   
5                               NaN          NaN              NaN   
6                               NaN          NaN              NaN   
7                               NaN          NaN              NaN   
..                              ...          ...              ...   
82                              0.0          0.0              0.0   
83                              0.0          0.0              0.0   
84                              0.0          0.0              0.0   
85                              0.0          0.0              0.0   
86                              0.0          0.0              0.0   

    1-Tetradecanol  n-Pentadecanol   1-Hexadecanol       Indole  Medium  
3              NaN             NaN             NaN          NaN     TSB  
4              NaN             NaN             NaN          NaN     TSB  
5              NaN             NaN             NaN          NaN     TSB  
6              NaN             NaN             NaN          NaN     TSB  
7              NaN             NaN             NaN          NaN     TSB  
..             ...             ...             ...          ...     ...  
82             0.0             0.0             0.0   60325589.0     TSB  
83         78672.0             0.0             0.0  107880324.0     TSB  
84         84426.0   

In [16]:
imputed = pd.read_csv('data/imputed_wide.csv', index_col='Unnamed: 0')

In [17]:
imputed.head()

Ethyl Acetate    Ethanol  Propanoic acid, ethyl ester  2-Pentanone  \
0        465374.0  1027715.0                 17989.407407    1289650.0   
1        193151.0  1050974.0                 17989.407407     504113.0   
2        403286.0  1850391.0                 17989.407407    1169501.0   
3        129833.0  5140770.0                 17989.407407    1926072.0   
4        117105.0  3422557.0                 17989.407407     246751.0   

     Decane  Methyl Isobutyl Ketone  Amylene hydrate  \
0  800581.0                324424.0          73015.0   
1  294680.0                189630.0              0.0   
2      15.0                228163.0          73558.0   
3  124282.0                     0.0         188367.0   
4       0.0                     0.0              0.0   

   Butanoic acid, 2-methyl-, methyl ester  Isobutyl acetate  \
0                           287247.703704      46016.203704   
1                           287247.703704      46016.203704   
2                           287247.703704      46016.203704   
3                           287247.703704      46016.203704   
4                           287247.703704      46016.203704   

   Methyl isovalerate  ...   1-Dodecanol  Methyl tetradecanoate  \
0                 0.0  ...  2.098782e+06           97878.333333   
1                 0.0  ...  2.098782e+06           97878.333333   
2                 0.0  ...  2.098782e+06           97878.333333   
3                 0.0  ...  2.098782e+06           97878.333333   
4                 0.0  ...  2.098782e+06           97878.333333   

    2-Pentadecanone  Tetradecanoic acid, ethyl ester  Hexadecanal  \
0       85753.37037                     10167.740741  94159.37037   
1       85753.37037                     10167.740741  94159.37037   
2       85753.37037                     10167.740741  94159.37037   
3       85753.37037                     10167.740741  94159.37037   
4       85753.37037                     10167.740741  94159.37037   

   n-Tridecan-1-ol  1-Tetradecanol  n-Pentadecanol   1-Hexadecanol      Indole  
0      85581.62963   586042.296296   173037.615385   662122.074074  82469063.0  
1      85581.62963   586042.296296   173037.615385   662122.074074  82469063.0  
2      85581.62963   586042.296296   173037.615385   662122.074074  82469063.0  
3      85581.62963   586042.296296   173037.615385   662122.074074  82469063.0  
4      85581.62963   586042.296296   173037.615385   662122.074074  82469063.0  

[5 rows x 67 columns]

In [83]:
data1['Medium'].value_counts()

LB     30
BHI    27
TSB    27
Name: Medium, dtype: int64

## We have our medium column now let's start our AutoML approach

We will need to number our medium column first instead of using categorical values.

In [18]:
data1['Medium'].value_counts()

LB     30
BHI    27
TSB    27
Name: Medium, dtype: int64

In [19]:
x = data1['Medium']
exit_status_map = {'LB': 0, 'BHI': 1, 'TSB': 2}
xyz = x.map(exit_status_map)

In [20]:
xyz

3     2
4     2
5     2
6     2
7     2
     ..
82    2
83    2
84    2
85    2
86    2
Name: Medium, Length: 84, dtype: int64

## 15% Split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(imputed, xyz, test_size=0.15)

In [22]:
automl = AutoML(algorithms=["Decision Tree", "Linear", "Random Forest", "Nearest Neighbors", "Xgboost"], total_time_limit=5*60)
automl.fit(X_train, y_train)

AutoML directory: AutoML_1
The task is multiclass_classification with evaluation metric logloss
AutoML will use algorithms: ['Decision Tree', 'Linear', 'Random Forest', 'Nearest Neighbors', 'Xgboost']
AutoML will ensemble available models
AutoML steps: ['simple_algorithms', 'default_algorithms', 'ensemble']
* Step simple_algorithms will try to check up to 2 models
1_DecisionTree logloss 0.842861 trained in 28.67 seconds
2_Linear logloss 0.223379 trained in 12.47 seconds
* Step default_algorithms will try to check up to 3 models
3_Default_Xgboost logloss 0.103531 trained in 14.95 seconds
4_Default_RandomForest logloss 0.596239 trained in 13.91 seconds


X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
X does not have valid feature names, but KNeighborsClassifier was fitted with feature names


Exception while producing SHAP explanations. 'NoneType' object has no attribute 'shap_values'
Continuing ...
5_Default_NearestNeighbors logloss 0.527302 trained in 3.7 seconds
* Step ensemble will try to check up to 1 model
Ensemble logloss 0.103531 trained in 0.67 seconds
AutoML fit time: 111.81 seconds
AutoML best model: 3_Default_Xgboost


AutoML(algorithms=['Decision Tree', 'Linear', 'Random Forest',
                   'Nearest Neighbors', 'Xgboost'],
       total_time_limit=300)

In [24]:
# Cross-Validation for 15:85 split
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)
clf.score(X_test, y_test)

0.7692307692307693

In [25]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X_test, y_test, cv=4)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.38 accuracy with a standard deviation of 0.25


The least populated class in y has only 3 members, which is less than n_splits=4.


In [26]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_predicted = automl.predict(X_test)
print(confusion_matrix(y_test,y_predicted))
print(classification_report(y_test,y_predicted))
print(accuracy_score(y_test, y_predicted))

[[4 0 0]
 [0 6 0]
 [0 0 3]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         6
           2       1.00      1.00      1.00         3

    accuracy                           1.00        13
   macro avg       1.00      1.00      1.00        13
weighted avg       1.00      1.00      1.00        13

1.0


## 20% Split

In [27]:
X_train20, X_test20, y_train20, y_test20 = train_test_split(imputed, xyz, test_size=0.20)

In [28]:
automl = AutoML(algorithms=["Decision Tree", "Linear", "Random Forest", "Nearest Neighbors", "Xgboost"], total_time_limit=5*60)
automl.fit(X_train20, y_train20)

AutoML directory: AutoML_2
The task is multiclass_classification with evaluation metric logloss
AutoML will use algorithms: ['Decision Tree', 'Linear', 'Random Forest', 'Nearest Neighbors', 'Xgboost']
AutoML will ensemble available models
AutoML steps: ['simple_algorithms', 'default_algorithms', 'ensemble']
* Step simple_algorithms will try to check up to 2 models
1_DecisionTree logloss 1.008222 trained in 14.59 seconds
2_Linear logloss 0.483168 trained in 11.31 seconds
* Step default_algorithms will try to check up to 3 models
3_Default_Xgboost logloss 0.172534 trained in 13.74 seconds
4_Default_RandomForest logloss 0.809196 trained in 15.93 seconds


X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
X does not have valid feature names, but KNeighborsClassifier was fitted with feature names


Exception while producing SHAP explanations. 'NoneType' object has no attribute 'shap_values'
Continuing ...
5_Default_NearestNeighbors logloss 2.112121 trained in 4.09 seconds
* Step ensemble will try to check up to 1 model
Ensemble logloss 0.172534 trained in 0.32 seconds
AutoML fit time: 104.45 seconds
AutoML best model: 3_Default_Xgboost


AutoML(algorithms=['Decision Tree', 'Linear', 'Random Forest',
                   'Nearest Neighbors', 'Xgboost'],
       total_time_limit=300)

In [29]:
# Cross-Validation for 20:80 split
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1).fit(X_train20, y_train20)
clf.score(X_test20, y_test20)

0.8823529411764706

In [30]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X_test20, y_test20, cv=4)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.53 accuracy with a standard deviation of 0.04


The least populated class in y has only 3 members, which is less than n_splits=4.


In [31]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_predicted20 = automl.predict(X_test20)
print(confusion_matrix(y_test20,y_predicted20))
print(classification_report(y_test20,y_predicted20))
print(accuracy_score(y_test20, y_predicted20))

[[8 0 0]
 [0 5 1]
 [0 0 3]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.83      0.91         6
           2       0.75      1.00      0.86         3

    accuracy                           0.94        17
   macro avg       0.92      0.94      0.92        17
weighted avg       0.96      0.94      0.94        17

0.9411764705882353


## 25% Split

In [32]:
X_train25, X_test25, y_train25, y_test25 = train_test_split(imputed, xyz, test_size=0.25)

In [33]:
automl = AutoML(algorithms=["Decision Tree", "Linear", "Random Forest", "Nearest Neighbors", "Xgboost"], total_time_limit=5*60)
automl.fit(X_train25, y_train25)

AutoML directory: AutoML_3
The task is multiclass_classification with evaluation metric logloss
AutoML will use algorithms: ['Decision Tree', 'Linear', 'Random Forest', 'Nearest Neighbors', 'Xgboost']
AutoML will ensemble available models
AutoML steps: ['simple_algorithms', 'default_algorithms', 'ensemble']
* Step simple_algorithms will try to check up to 2 models
1_DecisionTree logloss 2.209508 trained in 15.22 seconds
2_Linear logloss 0.4325 trained in 11.24 seconds
* Step default_algorithms will try to check up to 3 models
3_Default_Xgboost logloss 0.232312 trained in 18.96 seconds
4_Default_RandomForest logloss 0.883075 trained in 21.52 seconds


X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
X does not have valid feature names, but KNeighborsClassifier was fitted with feature names


Exception while producing SHAP explanations. 'NoneType' object has no attribute 'shap_values'
Continuing ...
5_Default_NearestNeighbors logloss 1.504039 trained in 4.14 seconds
* Step ensemble will try to check up to 1 model
Ensemble logloss 0.210967 trained in 0.37 seconds
AutoML fit time: 119.68 seconds
AutoML best model: Ensemble


AutoML(algorithms=['Decision Tree', 'Linear', 'Random Forest',
                   'Nearest Neighbors', 'Xgboost'],
       total_time_limit=300)

In [34]:
# Cross-Validation for 25:75 split
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1).fit(X_train25, y_train25)
clf.score(X_test25, y_test25)

0.8571428571428571

In [35]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X_test25, y_test25, cv=4)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.67 accuracy with a standard deviation of 0.08


The least populated class in y has only 3 members, which is less than n_splits=4.


In [36]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_predicted25 = automl.predict(X_test25)
print(confusion_matrix(y_test25,y_predicted25))
print(classification_report(y_test25,y_predicted25))
print(accuracy_score(y_test25, y_predicted25))

[[10  0  0]
 [ 0  7  1]
 [ 0  0  3]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.88      0.93         8
           2       0.75      1.00      0.86         3

    accuracy                           0.95        21
   macro avg       0.92      0.96      0.93        21
weighted avg       0.96      0.95      0.95        21

0.9523809523809523


## 30% Split

In [37]:
X_train30, X_test30, y_train30, y_test30 = train_test_split(imputed, xyz, test_size=0.3)

In [38]:
automl = AutoML(algorithms=["Decision Tree", "Linear", "Random Forest", "Nearest Neighbors", "Xgboost"], total_time_limit=5*60)
automl.fit(X_train30, y_train30)

AutoML directory: AutoML_4
The task is multiclass_classification with evaluation metric logloss
AutoML will use algorithms: ['Decision Tree', 'Linear', 'Random Forest', 'Nearest Neighbors', 'Xgboost']
AutoML will ensemble available models
AutoML steps: ['simple_algorithms', 'default_algorithms', 'ensemble']
* Step simple_algorithms will try to check up to 2 models
1_DecisionTree logloss 5.61107 trained in 14.1 seconds
2_Linear logloss 0.762603 trained in 12.18 seconds
* Step default_algorithms will try to check up to 3 models
3_Default_Xgboost logloss 0.76506 trained in 13.01 seconds
4_Default_RandomForest logloss 0.979656 trained in 15.67 seconds


X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
X does not have valid feature names, but KNeighborsClassifier was fitted with feature names


Exception while producing SHAP explanations. 'NoneType' object has no attribute 'shap_values'
Continuing ...
5_Default_NearestNeighbors logloss 1.448546 trained in 4.09 seconds
* Step ensemble will try to check up to 1 model
Ensemble logloss 0.607099 trained in 0.59 seconds
AutoML fit time: 100.79 seconds
AutoML best model: Ensemble


AutoML(algorithms=['Decision Tree', 'Linear', 'Random Forest',
                   'Nearest Neighbors', 'Xgboost'],
       total_time_limit=300)

In [39]:
# Cross-Validation for 30:70 split
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1).fit(X_train30, y_train30)
clf.score(X_test30, y_test30)

0.8076923076923077

In [40]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X_test30, y_test30, cv=4)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.57 accuracy with a standard deviation of 0.25


In [42]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_predicted30 = automl.predict(X_test30)
print(confusion_matrix(y_test30,y_predicted30))
print(classification_report(y_test30,y_predicted30))
print(accuracy_score(y_test30, y_predicted30))

[[12  0  0]
 [ 0  8  1]
 [ 0  0  5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.89      0.94         9
           2       0.83      1.00      0.91         5

    accuracy                           0.96        26
   macro avg       0.94      0.96      0.95        26
weighted avg       0.97      0.96      0.96        26

0.9615384615384616


X does not have valid feature names, but KNeighborsClassifier was fitted with feature names


## 40% Split

In [43]:
X_train40, X_test40, y_train40, y_test40 = train_test_split(imputed, xyz, test_size=0.4)

In [44]:
automl = AutoML(algorithms=["Decision Tree", "Linear", "Random Forest", "Nearest Neighbors", "Xgboost"], total_time_limit=5*60)
automl.fit(X_train40, y_train40)

AutoML directory: AutoML_5
The task is multiclass_classification with evaluation metric logloss
AutoML will use algorithms: ['Decision Tree', 'Linear', 'Random Forest', 'Nearest Neighbors', 'Xgboost']
AutoML will ensemble available models
AutoML steps: ['simple_algorithms', 'default_algorithms', 'ensemble']
* Step simple_algorithms will try to check up to 2 models
1_DecisionTree logloss 4.695849 trained in 15.75 seconds
2_Linear logloss 0.615686 trained in 12.4 seconds
* Step default_algorithms will try to check up to 3 models
3_Default_Xgboost logloss 0.930856 trained in 12.09 seconds
4_Default_RandomForest logloss 1.03656 trained in 12.84 seconds


X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
X does not have valid feature names, but KNeighborsClassifier was fitted with feature names


Exception while producing SHAP explanations. 'NoneType' object has no attribute 'shap_values'
Continuing ...
5_Default_NearestNeighbors logloss 0.509122 trained in 4.4 seconds
* Step ensemble will try to check up to 1 model
Ensemble logloss 0.469081 trained in 0.31 seconds
AutoML fit time: 95.99 seconds
AutoML best model: Ensemble


AutoML(algorithms=['Decision Tree', 'Linear', 'Random Forest',
                   'Nearest Neighbors', 'Xgboost'],
       total_time_limit=300)

In [45]:
# Cross-Validation for 40:60 split
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1).fit(X_train40, y_train40)
clf.score(X_test40, y_test40)

0.7941176470588235

In [46]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X_test40, y_test40, cv=4)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.70 accuracy with a standard deviation of 0.14


In [47]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_predicted40 = automl.predict(X_test40)
print(confusion_matrix(y_test40,y_predicted40))
print(classification_report(y_test40,y_predicted40))
print(accuracy_score(y_test40, y_predicted40))

[[15  0  2]
 [ 0  8  3]
 [ 0  2  4]]
              precision    recall  f1-score   support

           0       1.00      0.88      0.94        17
           1       0.80      0.73      0.76        11
           2       0.44      0.67      0.53         6

    accuracy                           0.79        34
   macro avg       0.75      0.76      0.74        34
weighted avg       0.84      0.79      0.81        34

0.7941176470588235


X does not have valid feature names, but KNeighborsClassifier was fitted with feature names


## 50% Split

In [48]:
X_train50, X_test50, y_train50, y_test50 = train_test_split(imputed, xyz, test_size=0.5)

In [49]:
automl = AutoML(algorithms=["Decision Tree", "Linear", "Random Forest", "Nearest Neighbors", "Xgboost"], total_time_limit=5*60)
automl.fit(X_train50, y_train50)

AutoML directory: AutoML_6
The task is multiclass_classification with evaluation metric logloss
AutoML will use algorithms: ['Decision Tree', 'Linear', 'Random Forest', 'Nearest Neighbors', 'Xgboost']
AutoML will ensemble available models
AutoML steps: ['simple_algorithms', 'default_algorithms', 'ensemble']
* Step simple_algorithms will try to check up to 2 models
1_DecisionTree logloss 3.908896 trained in 16.17 seconds
2_Linear logloss 0.648711 trained in 11.4 seconds
* Step default_algorithms will try to check up to 3 models
3_Default_Xgboost logloss 0.418621 trained in 14.21 seconds
4_Default_RandomForest logloss 0.872037 trained in 14.16 seconds


X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
X does not have valid feature names, but KNeighborsClassifier was fitted with feature names


Exception while producing SHAP explanations. 'NoneType' object has no attribute 'shap_values'
Continuing ...
5_Default_NearestNeighbors logloss 2.934207 trained in 4.49 seconds
* Step ensemble will try to check up to 1 model
Ensemble logloss 0.389198 trained in 0.31 seconds
AutoML fit time: 99.64 seconds
AutoML best model: Ensemble


AutoML(algorithms=['Decision Tree', 'Linear', 'Random Forest',
                   'Nearest Neighbors', 'Xgboost'],
       total_time_limit=300)

In [50]:
# Cross-Validation for 50:50 split
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1).fit(X_train50, y_train50)
clf.score(X_test50, y_test50)

0.7142857142857143

In [51]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X_test50, y_test50, cv=4)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.76 accuracy with a standard deviation of 0.11


In [52]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_predicted50 = automl.predict(X_test50)
print(confusion_matrix(y_test50,y_predicted50))
print(classification_report(y_test50,y_predicted50))
print(accuracy_score(y_test50, y_predicted50))

[[16  2  0]
 [ 1 11  2]
 [ 2  1  7]]
              precision    recall  f1-score   support

           0       0.84      0.89      0.86        18
           1       0.79      0.79      0.79        14
           2       0.78      0.70      0.74        10

    accuracy                           0.81        42
   macro avg       0.80      0.79      0.80        42
weighted avg       0.81      0.81      0.81        42

0.8095238095238095


# Random Forest For Medium

## 15% RF Split

In [53]:
X_trainrf, X_testrf, y_trainrf, y_testrf = train_test_split(imputed, xyz, test_size=0.15, random_state=0)

In [54]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_trainrf, y_trainrf)
y_predrf = regressor.predict(X_testrf)

In [55]:
# Cross-Validation for 15:85 RF split
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1).fit(X_trainrf, y_trainrf)
clf.score(X_testrf, y_testrf)

1.0

In [56]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X_testrf, y_testrf, cv=4)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.54 accuracy with a standard deviation of 0.14


The least populated class in y has only 2 members, which is less than n_splits=4.


In [57]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_predictedrf = automl.predict(X_testrf)
print(confusion_matrix(y_testrf,y_predictedrf))
print(classification_report(y_testrf,y_predictedrf))
print(accuracy_score(y_testrf, y_predictedrf))

[[5 1 0]
 [0 2 0]
 [0 1 4]]
              precision    recall  f1-score   support

           0       1.00      0.83      0.91         6
           1       0.50      1.00      0.67         2
           2       1.00      0.80      0.89         5

    accuracy                           0.85        13
   macro avg       0.83      0.88      0.82        13
weighted avg       0.92      0.85      0.86        13

0.8461538461538461


## 20% RF Split

In [58]:
X_trainrf20, X_testrf20, y_trainrf20, y_testrf20 = train_test_split(imputed, xyz, test_size=0.2, random_state=0)

In [59]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_trainrf20, y_trainrf20)
y_predrf20 = regressor.predict(X_testrf20)

In [60]:
# Cross-Validation for 20:80 RF split
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1).fit(X_trainrf20, y_trainrf20)
clf.score(X_testrf20, y_testrf20)

1.0

In [61]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X_testrf20, y_testrf20, cv=4)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.61 accuracy with a standard deviation of 0.30


The least populated class in y has only 3 members, which is less than n_splits=4.


In [62]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_predictedrf20 = automl.predict(X_testrf20)
print(confusion_matrix(y_testrf20,y_predictedrf20))
print(classification_report(y_testrf20,y_predictedrf20))
print(accuracy_score(y_testrf20, y_predictedrf20))

[[6 1 0]
 [0 3 0]
 [0 1 6]]
              precision    recall  f1-score   support

           0       1.00      0.86      0.92         7
           1       0.60      1.00      0.75         3
           2       1.00      0.86      0.92         7

    accuracy                           0.88        17
   macro avg       0.87      0.90      0.87        17
weighted avg       0.93      0.88      0.89        17

0.8823529411764706


## 25% RF Split

In [63]:
X_trainrf25, X_testrf25, y_trainrf25, y_testrf25 = train_test_split(imputed, xyz, test_size=0.25, random_state=0)

In [64]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_trainrf25, y_trainrf25)
y_predrf25 = regressor.predict(X_testrf25)

In [65]:
# Cross-Validation for 25:75 RF split
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1).fit(X_trainrf25, y_trainrf25)
clf.score(X_testrf25, y_testrf25)

1.0

In [66]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X_testrf25, y_testrf25, cv=4)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.71 accuracy with a standard deviation of 0.11


The least populated class in y has only 3 members, which is less than n_splits=4.


In [67]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_predictedrf25 = automl.predict(X_testrf25)
print(confusion_matrix(y_testrf25,y_predictedrf25))
print(classification_report(y_testrf25,y_predictedrf25))
print(accuracy_score(y_testrf25, y_predictedrf25))

[[8 1 0]
 [0 3 0]
 [0 1 8]]
              precision    recall  f1-score   support

           0       1.00      0.89      0.94         9
           1       0.60      1.00      0.75         3
           2       1.00      0.89      0.94         9

    accuracy                           0.90        21
   macro avg       0.87      0.93      0.88        21
weighted avg       0.94      0.90      0.91        21

0.9047619047619048


## 30% RF Split

In [68]:
X_trainrf30, X_testrf30, y_trainrf30, y_testrf30 = train_test_split(imputed, xyz, test_size=0.3, random_state=0)

In [69]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_trainrf30, y_trainrf30)
y_predrf30 = regressor.predict(X_testrf30)

In [70]:
# Cross-Validation for 30:70 RF split
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1).fit(X_trainrf30, y_trainrf30)
clf.score(X_testrf30, y_testrf30)

0.9615384615384616

In [71]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X_testrf30, y_testrf30, cv=4)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.57 accuracy with a standard deviation of 0.09


In [72]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_predictedrf30 = automl.predict(X_testrf30)
print(confusion_matrix(y_testrf30,y_predictedrf30))
print(classification_report(y_testrf30,y_predictedrf30))
print(accuracy_score(y_testrf30, y_predictedrf30))

[[9 2 0]
 [0 5 0]
 [0 1 9]]
              precision    recall  f1-score   support

           0       1.00      0.82      0.90        11
           1       0.62      1.00      0.77         5
           2       1.00      0.90      0.95        10

    accuracy                           0.88        26
   macro avg       0.88      0.91      0.87        26
weighted avg       0.93      0.88      0.89        26

0.8846153846153846


## 40% RF Split

In [73]:
X_trainrf40, X_testrf40, y_trainrf40, y_testrf40 = train_test_split(imputed, xyz, test_size=0.4, random_state=0)

In [74]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_trainrf40, y_trainrf40)
y_predrf40 = regressor.predict(X_testrf40)

In [75]:
# Cross-Validation for 40:60 RF split
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1).fit(X_trainrf40, y_trainrf40)
clf.score(X_testrf40, y_testrf40)

0.9411764705882353

In [76]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X_testrf40, y_testrf40, cv=4)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.60 accuracy with a standard deviation of 0.15


In [77]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_predictedrf40 = automl.predict(X_testrf40)
print(confusion_matrix(y_testrf40,y_predictedrf40))
print(classification_report(y_testrf40,y_predictedrf40))
print(accuracy_score(y_testrf40, y_predictedrf40))

[[11  2  0]
 [ 0  7  0]
 [ 0  1 13]]
              precision    recall  f1-score   support

           0       1.00      0.85      0.92        13
           1       0.70      1.00      0.82         7
           2       1.00      0.93      0.96        14

    accuracy                           0.91        34
   macro avg       0.90      0.92      0.90        34
weighted avg       0.94      0.91      0.92        34

0.9117647058823529


## 50% RF Split

In [78]:
X_trainrf50, X_testrf50, y_trainrf50, y_testrf50 = train_test_split(imputed, xyz, test_size=0.5, random_state=0)

In [79]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_trainrf50, y_trainrf50)
y_predrf50 = regressor.predict(X_testrf50)

In [80]:
# Cross-Validation for 50:50 RF split
from sklearn import svm
clf = svm.SVC(kernel='linear', C=1).fit(X_trainrf50, y_trainrf50)
clf.score(X_testrf50, y_testrf50)

0.8809523809523809

In [81]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X_testrf50, y_testrf50, cv=4)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.74 accuracy with a standard deviation of 0.13


In [82]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_predictedrf50 = automl.predict(X_testrf50)
print(confusion_matrix(y_testrf50,y_predictedrf50))
print(classification_report(y_testrf50,y_predictedrf50))
print(accuracy_score(y_testrf50, y_predictedrf50))

[[12  2  0]
 [ 0 11  0]
 [ 0  1 16]]
              precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.79      1.00      0.88        11
           2       1.00      0.94      0.97        17

    accuracy                           0.93        42
   macro avg       0.93      0.93      0.92        42
weighted avg       0.94      0.93      0.93        42

0.9285714285714286
